#!/bin/sh
if [ ! -f /usr/lib/enigma2/python/Tools/KeyBindings.py.bak ]; then
	cp /usr/lib/enigma2/python/Tools/KeyBindings.py /usr/lib/enigma2/python/Tools/KeyBindings.py.bak
	cp /usr/lib/enigma2/python/Plugins/SystemPlugins/DreamOsCockpit/Tools/KeyBindings.py /usr/lib/enigma2/python/Tools/.
fi
	
echo "***********************************"
echo "*         DreamOsCockpit          *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "Plugin installed successfully."
echo "Please restart DreamOS now!"
echo ""
exit 0
